# Generated by Django 4.2.2 on 2023-06-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="contract_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="expense",
            name="contracted_company",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="expense",
            name="item_service",
            field=models.CharField(default="", max_length=200),
        ),
    ]
