# Generated by Django 4.2.2 on 2023-06-20 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "expenses",
            "0002_expense_contract_duration_expense_contracted_company_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="category",
            new_name="category_id",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="department",
            new_name="department_id",
        ),
    ]
