# Generated by Django 4.2.2 on 2023-06-20 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_rename_category_expense_category_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="category_id",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="department_id",
            new_name="department",
        ),
    ]
