# Generated by Django 4.2.2 on 2023-06-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0004_rename_category_id_expense_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="CNPJ",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="expense",
            name="item_service",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
